In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np
import warnings as wr 
wr.filterwarnings('ignore')

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

# Step 01 - Regression

In [8]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [9]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [10]:
y.head()

Weight
0  241.893563
1  162.310473
2  212.740856
3  220.042470
4  206.349801

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.30, random_state=123) #train_size = .70 

In [12]:
#check all shape here 
print('Shape of X_train = ', x_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', x_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5988, 2)
Shape of y_train =  (5988, 1)
Shape of X_test =  (2567, 2)
Shape of y_test =  (2567, 1)


In [13]:
x_train

Gender     Height
6811       0  63.068203
48         1  69.179858
72         1  69.663725
2762       1  68.141642
5262       0  61.752696
...      ...        ...
7382       0  62.485691
7763       0  66.317755
5218       0  63.319818
1346       1  68.997440
3582       1  66.445147

[5988 rows x 2 columns]

In [14]:
y_train

Weight
6811   93.424239
48    192.014335
72    177.200929
2762  170.799951
5262  112.909948
...          ...
7382  116.460807
7763  151.211972
5218  119.315988
1346  200.313016
3582  163.293387

[5988 rows x 1 columns]

In [15]:
x_test

Gender     Height
4025       1  69.201493
5899       0  69.246764
2943       1  72.707224
1769       1  69.963912
7863       0  67.828343
...      ...        ...
8092       0  60.414750
8003       0  56.105370
237        1  67.947570
3260       1  62.951150
685        1  72.454633

[2567 rows x 2 columns]

In [16]:
y_test

Weight
4025  176.220870
5899  168.218019
2943  204.365104
1769  191.065448
7863  173.360437
...          ...
8092  124.706690
8003   87.298869
237   177.347780
3260  145.694359
685   200.290005

[2567 rows x 1 columns]

In [17]:
from sklearn.linear_model import LinearRegression

In [18]:
lr = LinearRegression()
lr

LinearRegression()

In [19]:
lr.fit(x_train,y_train)

LinearRegression()

In [20]:
# y = mx+c 

# m -> slope of the equation/Coefficient
# c -> y intercept
# Y -> dependent variable
# X -> independent variable

In [21]:
m = lr.coef_ 
m

array([[19.51079387,  5.98461303]])

In [22]:
c = lr.intercept_ 
c

array([-245.71718659])

In [23]:
predcition = lr.predict(x_test)
predcition

array([[187.93776592],
       [168.69789799],
       [208.91820816],
       ...,
       [180.43352055],
       [150.53188162],
       [207.4065508 ]])

In [24]:
lr.predict([[1,69.881796]]) #4  1	69.881796

array([[192.00911444]])

In [25]:
lr_score=lr.score(x_train,y_train)
lr_score

0.8997829055636625

In [26]:
#MSE 
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [27]:
mean_squared_error(y_test,predcition)

101.13990010493346

In [28]:
mean_absolute_error(y_test, predcition)

7.894465961090847

# KNN Regressor weights="uniform"

In [29]:
from sklearn.neighbors import KNeighborsRegressor

In [30]:
K_nei_reg_uniform = KNeighborsRegressor(weights= 'uniform',n_neighbors=101)
K_nei_reg_uniform

KNeighborsRegressor(n_neighbors=101)

In [31]:
K_nei_reg_uniform.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=101)

In [32]:
predcition2 = K_nei_reg_uniform.predict(x_test)

In [33]:
mean_squared_error(y_test,predcition2)

105.02852156594057

In [34]:
mean_absolute_error(y_test,predcition2)

8.015097621619875

In [35]:
kr_uni_score = K_nei_reg_uniform.score(x_test,y_test)
kr_uni_score

0.8964961382621226

In [36]:
x_test.iloc[-1, :]

Gender     1.000000
Height    72.454633
Name: 685, dtype: float64

In [37]:
y_test.iloc[-1]

Weight    200.290005
Name: 685, dtype: float64

In [38]:
y_test.shape

(2567, 1)

In [39]:
K_nei_reg_uniform.predict([x_test.iloc[-1, :]])

array([[207.33315757]])

# KNN Regressor weights='distance'

In [40]:
K_neigh_distance = KNeighborsRegressor(weights= 'distance',n_neighbors=101)


In [41]:
K_neigh_distance.fit(x_train,y_train)

KNeighborsRegressor(n_neighbors=101, weights='distance')

In [42]:
predcition3 = K_neigh_distance.predict(x_test)

In [43]:
mean_squared_error(y_test,predcition3)

122.61370597767602

In [44]:
mean_absolute_error(y_test,predcition3)

8.711283198995789

In [45]:
kr_dis_score = K_neigh_distance.score(x_test,y_test)
kr_dis_score

0.879166231405873

In [46]:
predcition3

array([[187.24459225],
       [169.39618737],
       [208.15437831],
       ...,
       [178.97637581],
       [151.6374836 ],
       [207.7617104 ]])

In [47]:
y_test.shape

(2567, 1)

In [48]:
x_test.shape

(2567, 2)

# Step 02 - Classification

In [49]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [50]:
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [51]:
x.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [52]:
x_train1,x_test1,y_train1,y_test1 = train_test_split(x,y, test_size = .30, random_state = 0) #train_size = .70 

In [53]:
x_train1.head()

Height      Weight
3197  69.689848  186.377448
4394  66.299441  159.235988
7711  63.261527  126.426793
7019  62.035319  119.418135
898   67.272171  187.363366

# KNN Classifier weights='uniform'

In [54]:
from sklearn.neighbors import KNeighborsClassifier

In [55]:
k_nei_cls = KNeighborsClassifier(weights= 'uniform',n_neighbors=101)

In [56]:
k_nei_cls.fit(x_train1, y_train1)

KNeighborsClassifier(n_neighbors=101)

In [57]:
kc_uni_score = k_nei_cls.score(x_test1,y_test1)
kc_uni_score

0.9115699259836385

In [58]:
predcition4 = k_nei_cls.predict(x_test1)

In [59]:
predcition4

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [60]:
x_test1.iloc[-1, :]

Height     63.939973
Weight    139.495957
Name: 5034, dtype: float64

In [61]:
y_test1.iloc[-1]

Gender    0
Name: 5034, dtype: int64

In [62]:
k_nei_cls.predict([x_test1.iloc[-1, :]])

array([0], dtype=int64)

# KNN Classifier weights='distance'

In [63]:
k_nei_cls_dis = KNeighborsClassifier(weights= 'distance',n_neighbors=101)

In [64]:
k_nei_cls_dis.fit(x_train1, y_train1)

KNeighborsClassifier(n_neighbors=101, weights='distance')

In [65]:
kc_dis_score = k_nei_cls_dis.score(x_test1,y_test1)
kc_dis_score

0.913517724970783

In [66]:
predcition5 = k_nei_cls.predict(x_test1)
predcition5

array([1, 1, 0, ..., 1, 1, 0], dtype=int64)

In [67]:
k_nei_cls_dis.predict([x_test1.iloc[-1, :]])

array([0], dtype=int64)

# Compare Algorithm

In [68]:
print("Linear Regression:", lr_score)
print("KNN Regressor weights= uniform", kr_uni_score)
print("KNN Regressor weights=distance:", kr_dis_score)
print("KNN Classifier:", kc_uni_score)
print("KNN Classifier:", kc_dis_score)

Linear Regression: 0.8997829055636625
KNN Regressor weights= uniform 0.8964961382621226
KNN Regressor weights=distance: 0.879166231405873
KNN Classifier: 0.9115699259836385
KNN Classifier: 0.913517724970783
